INSERT INTO characteristics (id, full_name, description, name) VALUES
                                                                   (1, 'WEAPON SKILL', 'Weapon Skill measures your competence in all forms of close-quarters combat. Characters with high Weapon Skill are excellent warriors, renowned with a chainsword or even their bare hands. Weapon Skill is used when making a melee attack and defending in melee combat.', 'WS'),
                                                                   (2, 'BALLISTIC SKILL', 'Ballistic Skill measures your accuracy with all forms of ranged weapons. A high Ballistic Skill indicates a character is an excellent sharpshooter, someone to be rightly feared in any fire-fight or shootout. Ballistic Skill is used when making a ranged attack.', 'BS'),
                                                                   (3, 'STRENGTH', 'Strength measures your muscle and physical power. Characters with high Strength can lift heavy objects, climb sheer surfaces with ease, and deal more damage with melee weapons.', 'STR'),
                                                                   (4, 'TOUGHNESS', 'Toughness measures your health, stamina, and resistance. Exceptionally tough characters are hard to kill, can withstand poisons and toxins, and survive in the galaxy''s harshest environments.', 'TGH'),
                                                                   (5, 'AGILITY', 'This measures your physical coordination, reflexes, and overall body awareness. High Agility allows a character to move silently, act first in dangerous situations, and dodge incoming attacks.', 'AG'),
                                                                   (6, 'INTELLIGENCE', 'Intelligence is your acumen, reason, and general knowledge. A character with a high Intelligence can recall huge volumes of data, correlate esoteric clues, or determine if an ancient archaeotech relic is genuine or not.', 'INT'),
                                                                   (7, 'PERCEPTION', 'This measures your awareness and the acuteness of your senses. A character with high Perception can pick out a stray bolter shell casing left amidst an underhive morass, tell when someone is being deceitful, or be the first to spot danger.', 'PER'),
                                                                   (8, 'WILLPOWER', 'Willpower measures a character''s mental strength and resolve. High Willpower allows a character to overcome fear, and is called upon when wielding and resisting psychic powers.', 'WIL'),
                                                                   (9, 'FELLOWSHIP', 'Fellowship measures your persuasiveness, ability to lead, and force of personality. Having a good Fellowship makes for a character who can ingratiate themself into a gathering of suspicious forge menials, make skilled trades with wily vendors, or cow others into obedience.', 'FEL');