-- Imperium Maledictum Core Rulebook pp. 222–223
-- Mutations (roll d100)
INSERT INTO mutation (name, description, mutation_type, d100_range) VALUES
('Witch-mark',           'The character develops an obvious physical mark that betrays their connection to the warp — a third eye, an unblinking pupil on the palm, or a brand that seems to glow with inner light. All Interaction tests made against characters who can see the mark suffer a –10 penalty, but the character gains a +10 bonus to Intimidation tests.',
 'mutation', '01–05'),
('Wasted Frame',         'The character''s body withers and wastes away, their flesh becoming sunken and pallid. The character''s Strength Bonus is reduced by 1, but the character''s Agility Bonus is increased by 1.',
 'mutation', '06–10'),
('Lashing Tentacle',     'A sinuous tentacle erupts from the character''s body — perhaps from the wrist, shoulder, or back. The tentacle can be used to make unarmed attacks with a Damage of 1d10+Strength Bonus (I), and can be used to perform the Disarm and Grapple actions.',
 'mutation', '11–15'),
('Inhuman Beauty',       'The character takes on an eerie, otherworldly beauty that makes mortals uneasy. The character gains a +10 bonus to Charm tests, but all Interaction tests made by characters who suspect the character''s nature suffer a –10 penalty.',
 'mutation', '16–20'),
('Iron Skin',            'The character''s skin thickens and hardens, taking on the texture and colour of rusted iron. The character gains 1 point of Armour on all locations, but suffers a –10 penalty to all Agility tests.',
 'mutation', '21–25'),
('Extra Mouth',          'An additional mouth erupts somewhere on the character''s body — perhaps on their cheek, palm, or stomach. This mouth speaks unbidden, sometimes voicing the character''s hidden thoughts or whispering the secrets of others.',
 'mutation', '26–30'),
('Searing Blood',        'The character''s blood becomes superheated and caustic. Whenever the character suffers a hit that causes Blood Loss, each creature within 1 metre suffers 1d5 (E) Damage with the Spray quality.',
 'mutation', '31–35'),
('Living Shadow',        'The character''s shadow moves independently, sometimes acting in ways that don''t match the character''s movements. Once per scene, the character can use their shadow to perform a Sleight of Hand or Stealth test.',
 'mutation', '36–40'),
('Swollen Brute',        'The character''s body swells with unnatural muscle and bloated flesh. The character''s Strength Bonus is increased by 1, but they suffer a –10 penalty to Agility tests and their Size increases by one step.',
 'mutation', '41–45'),
('Extra Eye',            'An additional eye appears on the character''s body — often on the forehead, palm, or the back of the head. The character gains a +10 bonus to Awareness tests and cannot be Surprised.',
 'mutation', '46–50'),
('Twisted Horns',        'Bony protrusions erupt from the character''s skull, growing into twisted horns. The character can make a Gore attack (Damage 1d10+Strength Bonus, I, Primitive) and gains a +10 bonus to Intimidation tests.',
 'mutation', '51–55'),
('Daemonic Visage',      'The character''s face twists into something inhuman — their eyes glow, their teeth become fangs, and their features warp into a terrifying mask. The character gains a +20 bonus to Intimidation tests, but suffers a –20 penalty to all other Interaction tests unless masked.',
 'mutation', '56–60'),
('Digitigrade Legs',     'The character''s legs reshape themselves, becoming digitigrade like those of an animal. The character''s Movement is increased by 1, and they gain a +10 bonus to Athletics tests involving running or jumping.',
 'mutation', '61–65'),
('Feathers',             'The character grows a covering of feathers across part or all of their body. The character gains a +10 bonus to Stealth tests in environments where the feathers provide camouflage, and is immune to the effects of Extreme Cold.',
 'mutation', '66–70'),
('Warp Claws',           'The character''s fingers extend into razor-sharp talons of solidified warp energy. The character can make Claw attacks (Damage 1d10+Strength Bonus, R, Tearing) and can affect creatures that are immune to mundane weapons.',
 'mutation', '71–75'),
('Photonic Irregularity', 'The character partially phases in and out of reality. Ranged attacks against the character suffer a –10 penalty, and the character can pass through objects no more than a few centimetres thick once per round.',
 'mutation', '76–80'),
('Festering Wound',      'A wound appears on the character''s body that refuses to heal, constantly weeping foul fluid. The character permanently loses 1 Wound, but any creature that grapples with the character must pass a Toughness test or contract a Minor Disease.',
 'mutation', '81–85'),
('Lolling Tongue',       'The character''s tongue grows to an enormous length and takes on a life of its own, constantly writhing and tasting the air. The character gains a +10 bonus to Awareness tests based on smell or taste, and can speak in a disturbing, sibilant manner that grants a +5 bonus to Intimidation.',
 'mutation', '86–90'),
('Fleshmetal',           'Patches of the character''s skin transform into a dull metallic substance. The character gains 2 points of Armour on the affected locations and is immune to the effects of Extreme Heat on those areas, but their Agility is reduced by 5.',
 'mutation', '91–95'),
('Warp Regeneration',    'The character develops an uncanny ability to regenerate damage. At the start of each of the character''s turns, they regain 1 lost Wound. This regeneration does not function if the character is at 0 Wounds or is suffering from a Critical Wound.',
 'mutation', '96–00');

-- Malignancies (roll d100)
INSERT INTO mutation (name, description, mutation_type, d100_range) VALUES
('Dark-hearted',             'The character''s emotions become muted and their capacity for empathy withers. The character gains a +10 bonus to resist Fear and Pinning, but suffers a –10 penalty to all Fellowship-based tests.',
 'malignancy', '01–05'),
('Awful Cravings',           'The character develops an intense and disturbing craving — perhaps for raw meat, grave soil, or stranger things. Once per day, if the character cannot satisfy their craving, they suffer 1d5 Corruption Points.',
 'malignancy', '06–10'),
('Overwhelming Obsession',   'The character becomes fixated on a single subject or activity. The character gains a +10 bonus to any tests related to their obsession, but must pass a Willpower test to focus on anything else while the obsession is present.',
 'malignancy', '11–15'),
('Ill-fortuned',             'Misfortune seems to follow the character wherever they go. Once per session, the GM may force the character to re-roll any one successful test, taking the worse result.',
 'malignancy', '16–20'),
('Irrational Nausea',        'The character experiences waves of uncontrollable nausea triggered by seemingly random stimuli. Once per session, at the GM''s discretion, the character must pass a Toughness test or spend their next turn retching and unable to act.',
 'malignancy', '21–25'),
('Unshakable Paranoia',      'The character becomes convinced that they are being watched and plotted against. The character suffers a –10 penalty to all Interaction tests and must pass a Willpower test to trust any new individual.',
 'malignancy', '26–30'),
('Dark Whispers',            'The character hears whispers from the warp that only they can hear. These whispers occasionally provide useful information, granting a +10 bonus to Forbidden Lore (Warp) tests, but the character must pass a Willpower test each session or gain 1 Corruption Point.',
 'malignancy', '31–35'),
('Phantom Memories',         'The character is haunted by vivid memories of events that never happened — or that happened to someone else entirely. Once per session, the character must pass a Willpower test or become Stunned for one round as a memory overwhelms them.',
 'malignancy', '36–40'),
('Irrational Fear',          'The character develops an intense, irrational fear of something mundane. Whenever they encounter their fear, they must pass a Fear test as though confronting a creature with Fear (1).',
 'malignancy', '41–45'),
('Blackouts',                'The character experiences episodes where they lose consciousness or enter a fugue state. Once per session, the GM may declare that the character experienced a blackout, with no memory of what occurred during it.',
 'malignancy', '46–50'),
('Morbid Fascination',       'The character develops an unhealthy fascination with death and suffering. The character gains a +10 bonus to Medicae tests, but must pass a Willpower test to avoid stopping to study the dead or dying when encountered.',
 'malignancy', '51–55'),
('Wheels Within Wheels',     'The character becomes obsessed with finding hidden patterns and conspiracies. They gain a +10 bonus to Scrutiny tests, but must pass a Willpower test to accept that something is exactly as it appears.',
 'malignancy', '56–60'),
('Inescapable Itch',         'The character suffers from a constant, maddening itch that cannot be relieved. The character suffers a –5 penalty to all Agility tests as they are constantly distracted, and must pass a Willpower test to maintain concentration for extended periods.',
 'malignancy', '61–65'),
('Warp Sense',               'The character develops an uncomfortable sensitivity to warp phenomena. The character can detect the presence of psykers and warp entities within 10 metres, but must pass a Willpower test when in the presence of strong warp emanations or gain 1 Corruption Point.',
 'malignancy', '66–70'),
('The Eyes',                 'The character becomes aware that something is watching them through other people''s eyes. The character suffers a –10 penalty to Willpower tests in crowded areas and gains a +10 bonus to Awareness when alone.',
 'malignancy', '71–75'),
('Void Gaze',                'The character''s eyes take on an unsettling quality — distant, unfocused, as though seeing something beyond the physical world. The character gains a +10 bonus to resist Fear but suffers a –10 penalty to social tests as others find their gaze deeply unsettling.',
 'malignancy', '76–80'),
('Ashen Taste',              'All food and drink tastes of ash to the character. They must pass a Toughness test each day or suffer 1 level of Fatigue as their appetite fails. They gain a +10 bonus to resist ingested poisons.',
 'malignancy', '81–85'),
('Dark Prophecies',          'The character receives unwanted visions of terrible futures. Once per session, the GM may reveal a brief, cryptic vision of what is to come. Once per session, the character may re-roll one test, but must accept the new result.',
 'malignancy', '86–90'),
('Warp Patron',              'Something in the warp has taken notice of the character and considers itself their patron. The character may call on this patron once per session for a +20 bonus to one test, but doing so costs 1d5 Corruption Points.',
 'malignancy', '91–95'),
('Psychic Awakening',        'Latent psychic potential erupts in the character. The character gains the Psyniscience skill at Rank 1 and may manifest one minor psychic power chosen by the GM, but gains 1d5 Corruption Points immediately and must register with the Inquisition.',
 'malignancy', '96–00');